/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#4f606f",
        "inverse-on-surface": "#f0f1f3",
        "surface-container-high": "#e7e8ea",
        "background": "#f8f9fb",
        "on-secondary-fixed-variant": "#374957",
        "surface-dim": "#d9dadc",
        "on-primary-fixed-variant": "#0040a2",
        "tertiary": "#004b58",
        "surface": "#f8f9fb",
        "on-secondary-container": "#536573",
        "primary-container": "#0052cc",
        "surface-tint": "#0c56d0",
        "on-error-container": "#93000a",
        "surface-container": "#edeef0",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fb",
        "outline": "#737685",
        "on-tertiary-fixed-variant": "#004e5d",
        "tertiary-fixed-dim": "#5dd6f3",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#b2c5ff",
        "tertiary-container": "#006476",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c3c6d6",
        "on-tertiary-fixed": "#001f26",
        "on-primary-container": "#c4d2ff",
        "surface-container-highest": "#e1e2e4",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "secondary-fixed": "#d2e5f6",
        "surface-variant": "#e1e2e4",
        "primary-fixed": "#dae2ff",
        "on-secondary-fixed": "#0a1d2a",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#adecff",
        "surface-container-low": "#f3f4f6",
        "secondary-fixed-dim": "#b6c9da",
        "on-surface": "#191c1e",
        "primary": "#003d9b",
        "on-background": "#191c1e",
        "on-tertiary-container": "#70e2ff",
        "on-surface-variant": "#434654",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#cfe2f3"
      },
      borderRadius: {
        "none": "0",
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
        "full": "9999px",
      },
      boxShadow: {
        'premium': '0 25px 50px -12px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      },
      spacing: {
        "gutter": "24px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px",
        "xl": "32px",
        "margin": "32px",
        "base": "4px",
        "md": "16px"
      },
      fontFamily: {
        "h1": ["Manrope"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Manrope"],
        "h2": ["Manrope"],
        "label-caps": ["Inter"],
        "sans": ["Plus Jakarta Sans", "Inter", "sans-serif"]
      },
      fontSize: {
        "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600"}],
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
